### Get All Users
GET http://localhost:8080/api/users
Accept: application/json

### Get User by Specific ID - John Doe
GET http://localhost:8080/api/users/a0fda7a4-7572-4fba-a550-4890f0d9b101
Accept: application/json

### Custom Search Users by Name
GET http://localhost:8080/api/users/search=Cha
Accept: application/json

### Create User
POST http://localhost:8080/api/users/create
Content-Type: application/json
Accept: application/json

{
  "firstName": "Charlie",
  "lastName": "Brown3"
}

### Update User - Jane Smith
PUT http://localhost:8080/api/users/a0fda7a4-7572-4fba-a550-4890f0d9b101/update
Content-Type: application/json
Accept: application/json

{
  "firstName": "Jane",
  "lastName": "Doe"
}

### Delete User - Alice Johnson
DELETE http://localhost:8080/api/users/f80c70aa-fad9-4e9d-bf77-625de2ec4c05/delete
Accept: application/json
